# Generated by Django 5.2.7 on 2025-10-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="current_mode",
            field=models.CharField(default="hunter", max_length=50),
        ),
    ]
