# Generated by Django 5.2.7 on 2025-10-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_playerprofile_current_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="ai_memory",
            field=models.JSONField(default=list),
        ),
    ]
